---
- hosts: all
  roles:
  - java-role
- hosts: elastic1
  roles:
  - elastic-role
- hosts: elastic1
  roles:
  - kibana-role


# - name: Install Java
#   hosts: all
#   tasks:
#     - name: Upload .tar.gz file containing binaries from local storage
#       copy:
#         src: "files/{{ java_oracle_jdk_package }}"
#         dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
#         mode: 0644
#       register: download_java_binaries
#       until: download_java_binaries is succeeded
#       tags: java
#     - name: Extract java in the installation directory
#       unarchive:
#         copy: false
#         src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
#         dest: "{{ java_home }}"
#         extra_opts: [--strip-components=1]
#         mode: 0644
#         # remote_src: yes
#       tags:
#         - skip_ansible_lint
#         - java
#     - name: Export environment variables
#       template:
#         src: jdk.sh.j2
#         dest: /etc/profile.d/jdk.sh
#         mode: 0644
#       tags: java
# # - name: Install Elasticsearch
# #   hosts: elastic1
# #   vars_files:
# #     - group_vars/elasticsearch/vars.yml
# #   tasks:
# #     - name: Create directrory for Elasticsearch
# #       file:
# #         state: directory
# #         path: "{{ elastic_home }}"
# #         mode: 0644
# #       tags: elastic
# #     - name: Copy elastik File in tmp
# #       copy:
# #         src: "files/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
# #         dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
# #         mode: 0644
# #     - name: Extract Elasticsearch in the installation directory
# #       unarchive:
# #         copy: false
# #         src: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
# #         dest: "{{ elastic_home }}"
# #         creates: "{{ elastic_home }}/bin/elasticsearch"
# #         # remote_src: yes
# #       tags:
# #         - skip_ansible_lint
# #         - elastic
# #     - name: Set environment Elastic
# #       template:
# #         src: templates/elk.sh.j2
# #         dest: /etc/profile.d/elk.sh
# #         mode: 0644
# #       tags: elastic
# - name: Install kibana
#   hosts: elastic1
#   vars_files:
#     - group_vars/kibana/vars.yml
#   tasks:
#     - name: Copy kibana File in tmp
#       copy:
#         src: files/kibana-{{ kibana_version }}-linux-x86_64.tar.gz
#         dest: /tmp
#         mode: 0644
#     - name: Create directrory for kibana
#       file:
#         state: directory
#         path: "{{ kibana_home }}"
#         mode: 0644
#       tags: kibana
#     - name: Extract Kibana in the installation directory
#       unarchive:
#         copy: false
#         src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
#         dest: "{{ kibana_home }}"
#         extra_opts: [--strip-components=1]
#         creates: "{{ kibana_home }}/bin/kibana"
#       tags:
#         - skip_ansible_lint
#         - kibana
#     - name: Set environment Kibana
#       template:
#         src: templates/kib.sh.j2
#         dest: /etc/profile.d/kib.sh
#         mode: 0644
#       tags: kibana
