---
# tasks file for java-role
- name: Create directrory for Java
  file:
    state: directory
    path: "{{ java_home }}"
    mode: 0644
- name: Upload .tar.gz file containing binaries from local storage
  copy:
    src: "files/{{ java_oracle_jdk_package }}"
    dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
    mode: 0644
  register: download_java_binaries
  until: download_java_binaries is succeeded
  tags: java
- name: Extract java in the installation directory
  unarchive:
    copy: false
    src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
    dest: "{{ java_home }}"
    extra_opts: [--strip-components=1]
    mode: 0644
    # remote_src: yes
  tags:
    - skip_ansible_lint
    - java
- name: Export environment variables
  template:
    src: jdk.sh.j2
    dest: /etc/profile.d/jdk.sh
    mode: 0644
  tags: java
