---
  el:
    hosts:
      elastic1:
        ansible_connection: docker
  deb:
    hosts:
      ubuntu:
        ansible_connection: docker
  local:
      hosts:
        localhost:
          ansible_connection: local
